"""Add unique constraint for spot_index per lot

Revision ID: b21bcb6e8ba5
Revises: fa745a58a63a
Create Date: 2025-07-10 19:58:33.683674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21bcb6e8ba5'
down_revision = 'fa745a58a63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_lot_spot_index', ['lot_id', 'spot_index'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.drop_constraint('unique_lot_spot_index', type_='unique')

    # ### end Alembic commands ###
