"""Added unique constraint to spot_index per lot

Revision ID: ef2cd391628f
Revises: b21bcb6e8ba5
Create Date: 2025-07-10 20:45:29.331922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2cd391628f'
down_revision = 'b21bcb6e8ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.alter_column('spot_index',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.alter_column('spot_index',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
