"""Add archived fields to Reservation

Revision ID: fa745a58a63a
Revises: 0962fcf69606
Create Date: 2025-07-10 13:33:08.635814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa745a58a63a'
down_revision = '0962fcf69606'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        op.drop_constraint('fk_parkingSpot_lot', 'parking_spot', type_='foreignkey')
        op.create_foreign_key(
            'fk_parkingSpot_lot',
            'parking_spot',
            'parking_lot',
            ['lot_id'],
            ['lot_id'],
            ondelete='CASCADE'
        )

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_primary_location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('archived_spot_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('archived_lot_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('archived_lot_id')
        batch_op.drop_column('archived_spot_id')
        batch_op.drop_column('archived_primary_location')

    with op.batch_alter_table('parking_spot', schema=None) as batch_op:
        batch_op.drop_constraint('fk_parkingSpot_lot', type_='foreignkey')
        batch_op.create_foreign_key('fk_parkingSpot_lot', 'parking_lot', ['lot_id'], ['lot_id'])

    # ### end Alembic commands ###
